spring.application.name=javaready-backend

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# MYSQL - ACER COMPUTER
# ===============================
spring.datasource.url=jdbc:mysql://192.168.0.117:3306/javaready?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:remoteuser}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
javaready.jwt.secret=${JWT_SECRET:CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_FOR_JAVAREADY}
javaready.jwt.expiration=86400000
