spring.application.name=javaready-backend

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# MYSQL DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://javaready-mysql-javaready2026.j.aivencloud.com:26871/defaultdb?sslMode=REQUIRED&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:avnadmin}
spring.datasource.password=${DB_PASSWORD:}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT CONFIGURATION
# ===============================
javaready.jwt.secret=${JWT_SECRET:CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_FOR_JAVAREADY}
javaready.jwt.expiration=86400000
